name: diffinf
channels:
  - conda-forge
  - nvidia
  - huggingface
 # - defaults
dependencies:
  - python=3.10.9
  - cudatoolkit=11.8
  - accelerate=0.29.3
  - diffusers=0.29.1
  - transformers=4.41.2
  - numpy=1.26
  - pandas=1.5.3
  - matplotlib
  - jupyterlab
  - pip