unet:
  image_size: 512
  dim: 256
  num_classes: 6
  dim_mults:
    - 1
    - 2
    - 4
  channels: 4
  resnet_block_groups: 2
  block_per_layer: 2
  
dm:
  data_folder: '../pathology-datasets/DRSK/init_dataset/dm-training-data'
  timesteps: 1000
  sampling_timesteps: 250
  batch_size: 32
  lr: 0.0001
  train_num_steps: 50000
  save_sample_every: 10000
  gradient_accumulate_every: 1
  save_loss_every: 1000
  num_samples: 4
  num_workers: 32
  results_folder: './logs/model_init'
  milestone: null