unet:
  image_size: 512
  dim: 256
  num_classes: 5
  dim_mults:
    - 1
    - 2
    - 4
  channels: 4
  resnet_block_groups: 2
  block_per_layer: 2
  
dm:
  data_folder: '../pathology-datasets/DRSK/full_dataset/labeled-data'
  timesteps: 1000
  sampling_timesteps: 250
  batch_size: 64
  lr: 0.0001
  train_num_steps: 100000
  save_sample_every: 100
  save_milestone_every: 5000
  gradient_accumulate_every: 2
  save_loss_every: 1000
  num_samples: 4
  num_workers: 32
  results_folder: './logs/drsk_512x256_5class_20240120_0805'
  milestone: null
  extra_data_path: '../pathology-datasets/DRSK/full_dataset/unconditional-data'