unet:
  image_size: 512
  dim: 256
  num_classes: 5
  dim_mults:
    - 1
    - 2
    - 4
  channels: 4
  resnet_block_groups: 2
  block_per_layer: 2
  
dm:
  data_folder: '../pathology-datasets/DRSK/full_dataset/labeled-data'
  timesteps: 1000
  sampling_timesteps: 250
  batch_size: 4
  lr: 0.0001
  train_num_steps: 2
  save_sample_every: 2
  gradient_accumulate_every: 1
  save_milestone_every: 1000
  save_loss_every: 2
  num_samples: 4
  num_workers: 16
  results_folder: './logs/short_test'
  milestone: null
  extra_data_path: '../pathology-datasets/DRSK/full_dataset/unconditional-data'
  debug: true  # Add this line